#############################################################################
# Makefile for building: SVMLearn
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? ??? 5 22:53:50 2013
# Project:  ../SVMLearn/SVMLearn.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../SVMLearn/SVMLearn.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
# DEFINES       = -DQT_WEBKIT
CFLAGS        = -pipe -std=c++0x -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W $(DEFINES)
# INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../SVMLearn -I../SVMLearn -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../SVMLearn/main.cpp \
		../SVMLearn/svm.cpp \
		../SVMLearn/problem.cpp \
		../SVMLearn/model.cpp \
		../SVMLearn/kernels.cpp \
		../SVMLearn/kernel_params.cpp \
		../SVMLearn/feature_node.cpp \
		../SVMLearn/eval_measures.cpp \
		../SVMLearn/category_map.cpp 
OBJECTS       = main.o \
		svm.o \
		problem.o \
		model.o \
		kernels.o \
		kernel_params.o \
		feature_node.o \
		eval_measures.o \
		category_map.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../SVMLearn/SVMLearn.pro
QMAKE_TARGET  = SVMLearn
DESTDIR       = 
TARGET        = SVMLearn

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../SVMLearn/SVMLearn.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../SVMLearn/SVMLearn.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile ../SVMLearn/SVMLearn.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SVMLearn1.0.0 || $(MKDIR) .tmp/SVMLearn1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SVMLearn1.0.0/ && (cd `dirname .tmp/SVMLearn1.0.0` && $(TAR) SVMLearn1.0.0.tar SVMLearn1.0.0 && $(COMPRESS) SVMLearn1.0.0.tar) && $(MOVE) `dirname .tmp/SVMLearn1.0.0`/SVMLearn1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SVMLearn1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: ../SVMLearn/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../SVMLearn/main.cpp

svm.o: ../SVMLearn/svm.cpp ../SVMLearn/model.h \
		../SVMLearn/problem.h \
		../SVMLearn/category_map.h \
		../SVMLearn/feature_node.h \
		../SVMLearn/kernels.h \
		../SVMLearn/svm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svm.o ../SVMLearn/svm.cpp

problem.o: ../SVMLearn/problem.cpp ../SVMLearn/category_map.h \
		../SVMLearn/feature_node.h \
		../SVMLearn/problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o ../SVMLearn/problem.cpp

model.o: ../SVMLearn/model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o ../SVMLearn/model.cpp

kernels.o: ../SVMLearn/kernels.cpp ../SVMLearn/feature_node.h \
		../SVMLearn/kernels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kernels.o ../SVMLearn/kernels.cpp

kernel_params.o: ../SVMLearn/kernel_params.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kernel_params.o ../SVMLearn/kernel_params.cpp

feature_node.o: ../SVMLearn/feature_node.cpp ../SVMLearn/feature_node.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o feature_node.o ../SVMLearn/feature_node.cpp

eval_measures.o: ../SVMLearn/eval_measures.cpp ../SVMLearn/problem.h \
		../SVMLearn/category_map.h \
		../SVMLearn/feature_node.h \
		../SVMLearn/eval_measures.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eval_measures.o ../SVMLearn/eval_measures.cpp

category_map.o: ../SVMLearn/category_map.cpp ../SVMLearn/category_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o category_map.o ../SVMLearn/category_map.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

